
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Marius
 */
public class Cautare extends javax.swing.JFrame {
 
   int x=0;
    Statement st=null;
      Conectare c = new Conectare("sun.jdbc.odbc.JdbcOdbcDriver","jdbc:odbc:BD");
    public Cautare() {
   initComponents();
        try{
        st = c.connect().createStatement();
        System.out.println(c.connect().toString());
        }
        catch (Exception ex){
            
            }
        }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jRadioButton1 = new javax.swing.JRadioButton();
        Listeaza_tot = new javax.swing.JButton();
        vinde = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tabel_Listare = new javax.swing.JTable();
        jButton4 = new javax.swing.JButton();
        prospect = new javax.swing.JTextField();
        nume_vanzare = new javax.swing.JTextField();
        unitati_vanzare = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cauta_nume = new javax.swing.JTextField();
        cauta_cod = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        simptome_client = new javax.swing.JTextField();
        pret_prod = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        Listeaza_dupacriterii = new javax.swing.JButton();

        jRadioButton1.setText("jRadioButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        Listeaza_tot.setIcon(new javax.swing.ImageIcon("C:\\Users\\Marius\\Documents\\NetBeansProjects\\Licenta\\table.png")); // NOI18N
        Listeaza_tot.setText("Listeaza toate produsele");
        Listeaza_tot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Listeaza_totActionPerformed(evt);
            }
        });

        vinde.setText("Vinde");
        vinde.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vindeActionPerformed(evt);
            }
        });

        Tabel_Listare.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(Tabel_Listare);

        jButton4.setIcon(new javax.swing.ImageIcon("C:\\Users\\Marius\\Documents\\NetBeansProjects\\Licenta\\Places-folder-open-icon.png")); // NOI18N
        jButton4.setText("Deschide prospect           ");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        nume_vanzare.setText("Nume produs");

        unitati_vanzare.setText("Unitati vandute");

        jPanel1.setBackground(new java.awt.Color(227, 227, 227));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Marius\\Documents\\NetBeansProjects\\Licenta\\Places-folder-saved-search-icon.png")); // NOI18N
        jLabel1.setText("         Cauta produs");

        jLabel3.setText("Dupa cod");

        jLabel2.setText("Dupa nume");

        jLabel8.setText("Pret <");

        jLabel7.setText("Simptome");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel4.setText("Cauta dupa simptome si pret");

        jButton1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Marius\\Documents\\NetBeansProjects\\Licenta\\k-get-list-icon.png")); // NOI18N
        jButton1.setText("Listeaza produsul cautat    ");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        Listeaza_dupacriterii.setText("Listeaza");
        Listeaza_dupacriterii.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Listeaza_dupacriteriiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel4))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(cauta_cod, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(cauta_nume, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(76, 76, 76)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(simptome_client, javax.swing.GroupLayout.DEFAULT_SIZE, 124, Short.MAX_VALUE)
                                    .addComponent(pret_prod)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Listeaza_dupacriterii, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(simptome_client, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cauta_nume, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pret_prod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel2)
                    .addComponent(cauta_cod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(Listeaza_dupacriterii, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jScrollPane1)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(vinde, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, 30, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(prospect)
                            .addComponent(nume_vanzare)
                            .addComponent(unitati_vanzare, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(Listeaza_tot, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(51, 51, 51))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Listeaza_tot)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton4)
                    .addComponent(prospect, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(nume_vanzare, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(unitati_vanzare, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(vinde, javax.swing.GroupLayout.DEFAULT_SIZE, 51, Short.MAX_VALUE))
                .addGap(90, 90, 90))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
      try{
        String sql5= "SELECT * FROM MEDICAMENT WHERE COD_MEDICAMENT ='"+cauta_nume.getText()+"'and DENUMIRE_MEDICAMENT='"+cauta_cod.getText()+"'";
         ResultSet rs = st.executeQuery(sql5);
          System.out.println(sql5);
          System.out.println(rs);
            Tabel_Listare.setModel(DbUtils.resultSetToTableModel(rs));
         if(rs.next())
         {
           
       
         System.out.println("S-a gasit!");
         }
         else
         {
        
         System.out.println("Nu s-a gasit nimic!");
         }
      }
         catch(Exception ex)
         {
             
             
         }
   

    }//GEN-LAST:event_jButton1ActionPerformed

    private void Listeaza_totActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Listeaza_totActionPerformed
 try{
        String sql = "Select COD_MEDICAMENT,DENUMIRE_MEDICAMENT,COD_SIMPTOME,NR_UNITATI,COD_CATEGORII_VARSTA,PRET_MEDICAMENT,DATA_EXP,COMPENSARE from  MEDICAMENT";
         ResultSet rs = st.executeQuery(sql);
         Tabel_Listare.setModel(DbUtils.resultSetToTableModel(rs));
        }
        catch(Exception ex)
        {
        
        }        // TODO add your handling code here:
    }//GEN-LAST:event_Listeaza_totActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
      try
        {
       Runtime.getRuntime().exec("rundll32 url.dll,FileProtocolHandler "+"C:\\Users\\Marius\\Downloads\\"+prospect.getText()+".pdf");
      
        }
        catch(Exception ex)
        {
        JOptionPane.showMessageDialog(null,"Nu se deschide!");
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void Listeaza_dupacriteriiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Listeaza_dupacriteriiActionPerformed
      try{
          String sql2="SELECT DENUMIRE_MEDICAMENT,PRET_MEDICAMENT,DENUMIRE_SIMPTOME FROM MEDICAMENT AS A INNER JOIN SIMPTOME AS B ON A.COD_SIMPTOME=B.COD_SIMPTOME WHERE DENUMIRE_SIMPTOME='"+simptome_client.getText()+"' AND PRET_MEDICAMENT<'"+pret_prod.getText()+"'";
     // String sql2= "SELECT * FROM MEDICAMENT WHERE PRET_MEDICAMENT < ='"+pret_prod.getText()+"'";
         ResultSet rs = st.executeQuery(sql2);
          System.out.println(rs);
         Tabel_Listare.setModel(DbUtils.resultSetToTableModel(rs));
      if(rs.next()){
      System.out.println("S-au gasit medicamente cu pretul mai mic decat cel dat");
      }
      }
      
      catch(Exception ex)
      {
      
      }
      
      /*
      
      try{
      String sql5="SELECT DENUMIRE_MEDICAMENT,PRET_MEDICAMENT,DENUMIRE_SIMPTOME FROM MEDICAMENT AS A INNER JOIN SIMPTOME AS B ON A.COD_SIMPTOME=B.COD_SIMPTOME WHERE DENUMIRE_SIMPTOME='"+simptome_client.getText()+"'";
      ResultSet rs = st.executeQuery(sql5);
      System.out.println(rs);
      Tabel_Listare.setModel(DbUtils.resultSetToTableModel(rs));
      }
      catch(Exception ex)
      {
      
      }*/
      
    }//GEN-LAST:event_Listeaza_dupacriteriiActionPerformed

    private void vindeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vindeActionPerformed
      //Tabel_Listare.getModel().setValueAt(50-Integer.parseInt(numar_produse.getText()), Tabel_Listare.getSelectedRow(), 3);
        try{
       
          //  String sql2 = "update Medicament2 set stoc='"+numar_produse.getText()+"' where cod='"+Tabel_Listare.getSelectedRow()+"'";
         String sql2= "SELECT NR_UNITATI FROM MEDICAMENT WHERE DENUMIRE_MEDICAMENT='"+nume_vanzare.getText()+"'";
         ResultSet rs = st.executeQuery(sql2);
System.out.println("Marius a facut asta azi--->"+rs);
         while(rs.next())
         {
             x=rs.getInt(WIDTH);
         System.out.println("Test========>"+x);
         
         }
//Tabel_Listare.setModel(DbUtils.resultSetToTableModel(rs));
        }
       catch(Exception ex)
       {
       
       }
        System.out.println("Val lui x"+x);
       
        
        try{
            System.out.println("Test la x="+x);
            int z=Integer.parseInt(unitati_vanzare.getText());
            int s=x-z;
            if(z>0 && x>z){
            System.out.println("Test la z="+z);
            System.out.println("Test la s="+s);
        String sql3="update MEDICAMENT set NR_UNITATI='"+s+"'where DENUMIRE_MEDICAMENT='"+nume_vanzare.getText()+"'";
       ResultSet  rs2 = st.executeQuery(sql3);
        // System.out.println(Tabel_Listare.getSelectedRow());
        }}
        catch(Exception ex)
        {
        
        }
       
    }//GEN-LAST:event_vindeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cautare.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cautare.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cautare.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cautare.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cautare().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Listeaza_dupacriterii;
    private javax.swing.JButton Listeaza_tot;
    private javax.swing.JTable Tabel_Listare;
    private javax.swing.JTextField cauta_cod;
    private javax.swing.JTextField cauta_nume;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField nume_vanzare;
    private javax.swing.JTextField pret_prod;
    private javax.swing.JTextField prospect;
    private javax.swing.JTextField simptome_client;
    private javax.swing.JTextField unitati_vanzare;
    private javax.swing.JButton vinde;
    // End of variables declaration//GEN-END:variables
}
